#!/usr/bin/env python3
"""Compile the order-2 Markov chain JSON into a C header that src/recipe.c embeds.

Usage: compile_markov.py markov-2.json markov_data.h

Input: {"w1 w2": {"w3": probability, ...}, ...}

Output: static const tables (no pointers, so no relocations at load time):

    starts[]      {threshold, word_a, word_b, state}   sentence-opening pairs
    states[]      {first, count}                       one per "w1 w2" key
    transitions[] {threshold, word, next}              next = state "w2 w3" or NONE
    words[]       {offset, len | SENTENCE_END}         into blob[]
    blob[]        concatenated UTF-8 words, no terminators

Thresholds are cumulative weights scaled to [0, 2^32 - 1]; the last one of each
run is exactly 2^32 - 1, so a uniform 32-bit draw always selects an entry.

Kept compatible with Python 3.5.
"""

import collections
import json
import sys

NONE = 0xFFFFFFFF
UINT32_MAX = 0xFFFFFFFF
SENTENCE_END = 0x80000000


def ends_sentence(word):
    return word.endswith(".") or word.endswith("!")


def thresholds(weights):
    total = float(sum(weights))
    out = []
    cumulative = 0.0
    for w in weights:
        cumulative += w
        out.append(min(UINT32_MAX, int(cumulative / total * UINT32_MAX)))
    out[-1] = UINT32_MAX
    return out


def load(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f, object_pairs_hook=collections.OrderedDict)


def build(markov):
    word_ids = collections.OrderedDict()

    def word_id(w):
        if w not in word_ids:
            word_ids[w] = len(word_ids)
        return word_ids[w]

    state_ids = dict((key, i) for i, key in enumerate(markov))

    states = []
    transitions = []
    for key, nexts in markov.items():
        w1, w2 = key.split(" ")
        word_id(w1)
        word_id(w2)
        words = list(nexts.keys())
        states.append((len(transitions), len(words)))
        for w3, t in zip(words, thresholds(list(nexts.values()))):
            transitions.append((t, word_id(w3), state_ids.get(w2 + " " + w3, NONE)))

    # Sentence-opening pairs (a, b): a follows a word ending in ".", b follows a,
    # and "a b" is a state. Weighted by summed transition probability (~ frequency).
    weights = collections.OrderedDict()
    for key, nexts in markov.items():
        w1, a = key.split(" ")
        if not w1.endswith(".") or ends_sentence(a):
            continue
        for b, p in nexts.items():
            if ends_sentence(b) or (a + " " + b) not in state_ids:
                continue
            weights[(a, b)] = weights.get((a, b), 0.0) + p
    if not weights:
        sys.exit("no sentence-start pairs found")
    starts = [
        (t, word_id(a), word_id(b), state_ids[a + " " + b])
        for (a, b), t in zip(weights.keys(), thresholds(list(weights.values())))
    ]

    blob = bytearray()
    words = []
    for w in word_ids:
        enc = w.encode("utf-8")
        if not enc or len(enc) > 255:
            sys.exit("bad word: %r" % w)
        words.append((len(blob), len(enc) | (SENTENCE_END if ends_sentence(w) else 0)))
        blob += enc

    return {
        "starts": starts,
        "states": states,
        "transitions": transitions,
        "words": words,
        "blob": bytes(blob),
        "max_word_len": max(len(w.encode("utf-8")) for w in word_ids),
    }


def rows(f, decl, items, per_line):
    f.write("%s = {\n" % decl)
    for i in range(0, len(items), per_line):
        f.write(",".join(items[i:i + per_line]))
        f.write(",\n")
    f.write("};\n\n")


def emit(model, path):
    def structs(rows_):
        return ["{%s}" % ",".join(str(v) for v in r) for r in rows_]

    with open(path, "w") as f:
        f.write("/* Generated by tools/compile_markov.py -- do not edit. */\n\n")
        f.write("#define N_STARTS %du\n" % len(model["starts"]))
        f.write("#define N_STATES %du\n" % len(model["states"]))
        f.write("#define N_TRANSITIONS %du\n" % len(model["transitions"]))
        f.write("#define N_WORDS %du\n" % len(model["words"]))
        f.write("#define MAX_WORD_LEN %du\n\n" % model["max_word_len"])
        rows(f, "static const struct start starts[N_STARTS]", structs(model["starts"]), 8)
        rows(f, "static const struct state states[N_STATES]", structs(model["states"]), 12)
        rows(f, "static const struct trans transitions[N_TRANSITIONS]",
             structs(model["transitions"]), 8)
        rows(f, "static const struct word words[N_WORDS]", structs(model["words"]), 12)
        rows(f, "static const unsigned char blob[%d]" % len(model["blob"]),
             [str(b) for b in model["blob"]], 32)


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: compile_markov.py markov-2.json markov_data.h")
    model = build(load(sys.argv[1]))
    emit(model, sys.argv[2])
    print("%s: %d starts, %d states, %d transitions, %d words"
          % (sys.argv[2], len(model["starts"]), len(model["states"]),
             len(model["transitions"]), len(model["words"])))


if __name__ == "__main__":
    main()
