/*
 * recipe: prints random recipes from an order-2 Markov chain.
 *
 *   recipe                 CGI: write one response to stdout and exit
 *   recipe --listen PATH   FastCGI server on a new Unix socket at PATH
 *   (socket activation)    FastCGI server on the socket passed in by systemd
 *
 * The FastCGI server forks a fresh child for every connection. The child reads
 * the request, writes one recipe and exits, so no per-request state survives.
 * The parent only accepts connections and holds the read-only tables. They are
 * copied into anonymous (ideally huge-page) memory once at startup, so a child
 * inherits them already mapped and takes no page faults to read them.
 *
 * The model is compiled in (markov_data.h, generated by tools/compile_markov.py):
 * nothing is opened or parsed at request time.
 *
 * Plain C99 + POSIX; builds with GCC 5.
 */

#define _POSIX_C_SOURCE 200809L
#define _DEFAULT_SOURCE /* glibc: MADV_HUGEPAGE */

#include <errno.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

#define NONE 0xffffffffu
#define SENTENCE_END 0x80000000u

#define MIN_WORDS 150 /* generate at least this many words after the start pair */
#define MAX_WORDS 300 /* ... then continue until a sentence ends, up to this many */

#define MAX_CHILDREN 64    /* concurrent requests; more connections wait in the backlog */
#define REQUEST_TIMEOUT 10 /* seconds a child may take before SIGALRM kills it */
#define HUGE_PAGE (2u << 20)

struct start { uint32_t threshold, word_a, word_b, state; };
struct state { uint32_t first, count; };
struct trans { uint32_t threshold, word, next; };
struct word { uint32_t offset, len_flags; };

#include "markov_data.h"

static const struct start *starts = data_starts;
static const struct state *states = data_states;
static const struct trans *transitions = data_transitions;
static const struct word *words = data_words;
static const unsigned char *blob = data_blob;

static const char content_header[] =
    "Content-Type: text/plain; charset=utf-8\r\n"
    "Cache-Control: no-store\r\n"
    "\r\n";

/* FastCGI record types and header size */
#define FCGI_BEGIN_REQUEST 1
#define FCGI_END_REQUEST 3
#define FCGI_STDIN 5
#define FCGI_STDOUT 6
#define FCGI_HEADER 8

/* A response is: FastCGI header, CGI headers + recipe, then an empty STDOUT
 * record and END_REQUEST (8 + 8 + 8 bytes). In CGI mode only the middle is sent. */
#define BODY_MAX (sizeof content_header - 1 + (MAX_WORDS + 2) * (MAX_WORD_LEN + 1))
typedef char body_fits_in_one_record[BODY_MAX <= 65535 ? 1 : -1];
static unsigned char response[FCGI_HEADER + BODY_MAX + 3 * FCGI_HEADER];

static uint64_t rng;

/* splitmix64 */
static uint32_t random32(void)
{
    uint64_t z = (rng += 0x9e3779b97f4a7c15ull);
    z = (z ^ (z >> 30)) * 0xbf58476d1ce4e5b9ull;
    z = (z ^ (z >> 27)) * 0x94d049bb133111ebull;
    return (uint32_t)((z ^ (z >> 31)) >> 32);
}

static void seed(int urandom)
{
    if (urandom >= 0 && read(urandom, &rng, sizeof rng) == (ssize_t)sizeof rng)
        return;
    {
        struct timespec ts;
        clock_gettime(CLOCK_REALTIME, &ts);
        rng = ((uint64_t)ts.tv_sec << 32) ^ (uint64_t)ts.tv_nsec ^ ((uint64_t)getpid() << 16);
    }
}

/* Binary search for the first entry with threshold >= r. The last threshold is
 * UINT32_MAX, so there always is one. */
static const struct start *pick_start(uint32_t r)
{
    uint32_t lo = 0, hi = N_STARTS - 1;
    while (lo < hi) {
        uint32_t mid = lo + (hi - lo) / 2;
        if (starts[mid].threshold < r)
            lo = mid + 1;
        else
            hi = mid;
    }
    return &starts[lo];
}

static const struct trans *pick_transition(const struct state *s, uint32_t r)
{
    const struct trans *t = &transitions[s->first];
    uint32_t lo = 0, hi = s->count - 1;
    while (lo < hi) {
        uint32_t mid = lo + (hi - lo) / 2;
        if (t[mid].threshold < r)
            lo = mid + 1;
        else
            hi = mid;
    }
    return &t[lo];
}

/* Appends a word at dst + *len; returns nonzero if it ends a sentence. */
static uint32_t append(unsigned char *dst, size_t *len, uint32_t id, int space)
{
    const struct word *w = &words[id];
    uint32_t n = w->len_flags & ~SENTENCE_END;
    if (space)
        dst[(*len)++] = ' ';
    memcpy(dst + *len, blob + w->offset, n);
    *len += n;
    return w->len_flags & SENTENCE_END;
}

/* Writes CGI headers and one recipe to dst; returns the length. */
static size_t generate(unsigned char *dst)
{
    size_t len = sizeof content_header - 1;
    const struct start *s;
    uint32_t state, sentence_end;
    int i;

    memcpy(dst, content_header, len);

    s = pick_start(random32());
    append(dst, &len, s->word_a, 0);
    sentence_end = append(dst, &len, s->word_b, 1);
    state = s->state;

    for (i = 0; i < MAX_WORDS && state != NONE; i++) {
        const struct trans *t;
        if (i >= MIN_WORDS && sentence_end)
            break;
        t = pick_transition(&states[state], random32());
        sentence_end = append(dst, &len, t->word, 1);
        state = t->next;
    }
    return len;
}

static int write_all(int fd, const unsigned char *p, size_t len)
{
    while (len > 0) {
        ssize_t n = write(fd, p, len);
        if (n <= 0)
            return -1;
        p += n;
        len -= (size_t)n;
    }
    return 0;
}

static unsigned char *fcgi_header(unsigned char *p, int type, unsigned id, size_t len)
{
    p[0] = 1; /* version */
    p[1] = (unsigned char)type;
    p[2] = (unsigned char)(id >> 8);
    p[3] = (unsigned char)id;
    p[4] = (unsigned char)(len >> 8);
    p[5] = (unsigned char)len;
    p[6] = 0; /* padding */
    p[7] = 0;
    return p + FCGI_HEADER;
}

/* Child: read one FastCGI request (up to its empty STDIN record), respond, return.
 * Request parameters and body are ignored; reading them fully matters because
 * closing a Unix socket with unread data makes the peer see ECONNRESET. */
static void serve(int conn, int urandom)
{
    static unsigned char in[FCGI_HEADER + 65535 + 255];
    size_t have = 0, len;
    unsigned id = 0;
    int began = 0, done = 0;
    unsigned char *p;

    alarm(REQUEST_TIMEOUT);
    while (!done) {
        ssize_t n = read(conn, in + have, sizeof in - have);
        if (n <= 0)
            return;
        have += (size_t)n;
        while (have >= FCGI_HEADER) {
            unsigned rid = (unsigned)in[2] << 8 | in[3];
            size_t clen = (size_t)in[4] << 8 | in[5];
            size_t rlen = FCGI_HEADER + clen + in[6];
            if (in[0] != 1)
                return;
            if (have < rlen)
                break;
            if (in[1] == FCGI_BEGIN_REQUEST && !began) {
                id = rid;
                began = 1;
            } else if (in[1] == FCGI_STDIN && began && rid == id && clen == 0) {
                done = 1;
                break;
            }
            memmove(in, in + rlen, have - rlen);
            have -= rlen;
        }
    }

    seed(urandom);
    len = generate(response + FCGI_HEADER);
    fcgi_header(response, FCGI_STDOUT, id, len);
    p = fcgi_header(response + FCGI_HEADER + len, FCGI_STDOUT, id, 0);
    p = fcgi_header(p, FCGI_END_REQUEST, id, 8);
    memset(p, 0, 8); /* app status 0, FCGI_REQUEST_COMPLETE */
    write_all(conn, response, (size_t)(p + 8 - response));
}

/* Copies the tables into anonymous memory, using transparent huge pages where
 * the kernel allows. fork() then shares them with every child through the page
 * tables: two or three huge-page entries rather than ~1000 small ones, and no
 * page faults in the child. On failure the tables stay in .rodata. */
static void tables_to_anonymous_memory(void)
{
    size_t total = sizeof data_starts + sizeof data_states + sizeof data_transitions +
                   sizeof data_words + sizeof data_blob;
    unsigned char *p;
    void *mem;

    total = (total + HUGE_PAGE - 1) / HUGE_PAGE * HUGE_PAGE;
    if (posix_memalign(&mem, HUGE_PAGE, total) != 0)
        return;
#ifdef MADV_HUGEPAGE
    madvise(mem, total, MADV_HUGEPAGE);
#endif
    /* Each table size is a multiple of 4, so every table stays 4-byte aligned. */
    p = mem;
    starts = memcpy(p, data_starts, sizeof data_starts);
    p += sizeof data_starts;
    states = memcpy(p, data_states, sizeof data_states);
    p += sizeof data_states;
    transitions = memcpy(p, data_transitions, sizeof data_transitions);
    p += sizeof data_transitions;
    words = memcpy(p, data_words, sizeof data_words);
    p += sizeof data_words;
    blob = memcpy(p, data_blob, sizeof data_blob);
}

static int server(int listener)
{
    int urandom = open("/dev/urandom", O_RDONLY);
    unsigned children = 0;

    if (urandom < 0)
        perror("recipe: /dev/urandom");
    tables_to_anonymous_memory();

    for (;;) {
        pid_t pid;
        int conn = accept(listener, NULL, NULL);
        if (conn < 0) {
            if (errno != EINTR && errno != ECONNABORTED) {
                struct timespec backoff = {0, 10000000};
                perror("recipe: accept");
                nanosleep(&backoff, NULL);
            }
            continue;
        }

        while (children > 0 && waitpid(-1, NULL, WNOHANG) > 0)
            children--;
        while (children >= MAX_CHILDREN && waitpid(-1, NULL, 0) > 0)
            children--;

        pid = fork();
        if (pid == 0) {
            close(listener);
            serve(conn, urandom);
            _exit(0);
        }
        if (pid < 0)
            perror("recipe: fork");
        else
            children++;
        close(conn);
    }
}

/* systemd socket activation: the listening socket is fd 3. */
static int systemd_socket(void)
{
    const char *pid = getenv("LISTEN_PID"), *fds = getenv("LISTEN_FDS");
    if (pid == NULL || fds == NULL || strtol(pid, NULL, 10) != (long)getpid() ||
        strtol(fds, NULL, 10) < 1)
        return -1;
    return 3;
}

static int unix_socket(const char *path)
{
    struct sockaddr_un addr;
    int fd;

    memset(&addr, 0, sizeof addr);
    addr.sun_family = AF_UNIX;
    if (strlen(path) >= sizeof addr.sun_path) {
        fprintf(stderr, "recipe: socket path too long\n");
        return -1;
    }
    strcpy(addr.sun_path, path);
    unlink(path);
    fd = socket(AF_UNIX, SOCK_STREAM, 0);
    if (fd < 0 || bind(fd, (struct sockaddr *)&addr, sizeof addr) != 0 ||
        listen(fd, SOMAXCONN) != 0) {
        perror("recipe: listen");
        return -1;
    }
    return fd;
}

int main(int argc, char **argv)
{
    int listener;

    if (argc == 3 && strcmp(argv[1], "--listen") == 0) {
        listener = unix_socket(argv[2]);
        return listener < 0 ? 1 : server(listener);
    }
    if (argc != 1) {
        fprintf(stderr, "usage: recipe [--listen SOCKET]\n");
        return 2;
    }
    listener = systemd_socket();
    if (listener >= 0)
        return server(listener);

    /* CGI */
    {
        int urandom = open("/dev/urandom", O_RDONLY);
        seed(urandom);
        size_t len = generate(response + FCGI_HEADER);
        return write_all(STDOUT_FILENO, response + FCGI_HEADER, len) == 0 ? 0 : 1;
    }
}
