/*
 * recipe: CGI program that prints one random recipe from an order-2 Markov chain.
 *
 * Runs once per request and exits; no state survives between requests. The model
 * is compiled in (markov_data.h, generated by tools/compile_markov.py), so it is
 * mapped from the page cache together with the executable: nothing is opened or
 * parsed at request time.
 *
 * Plain C99 + POSIX; builds with GCC 5.
 */

#include <fcntl.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

#define NONE 0xffffffffu
#define SENTENCE_END 0x80000000u

#define MIN_WORDS 150 /* generate at least this many words after the start pair */
#define MAX_WORDS 300 /* ... then continue until a sentence ends, up to this many */

struct start { uint32_t threshold, word_a, word_b, state; };
struct state { uint32_t first, count; };
struct trans { uint32_t threshold, word, next; };
struct word { uint32_t offset, len_flags; };

#include "markov_data.h"

static const char content_header[] =
    "Content-Type: text/plain; charset=utf-8\r\n"
    "Cache-Control: no-store\r\n"
    "\r\n";

static char out[sizeof content_header + (MAX_WORDS + 2) * (MAX_WORD_LEN + 1)];
static size_t len;

static uint64_t rng;

/* splitmix64 */
static uint32_t random32(void)
{
    uint64_t z = (rng += 0x9e3779b97f4a7c15ull);
    z = (z ^ (z >> 30)) * 0xbf58476d1ce4e5b9ull;
    z = (z ^ (z >> 27)) * 0x94d049bb133111ebull;
    return (uint32_t)((z ^ (z >> 31)) >> 32);
}

static void seed(void)
{
    int fd = open("/dev/urandom", O_RDONLY);
    if (fd >= 0) {
        ssize_t n = read(fd, &rng, sizeof rng);
        close(fd);
        if (n == (ssize_t)sizeof rng)
            return;
    }
    {
        struct timespec ts;
        clock_gettime(CLOCK_REALTIME, &ts);
        rng = ((uint64_t)ts.tv_sec << 32) ^ (uint64_t)ts.tv_nsec ^ ((uint64_t)getpid() << 16);
    }
}

/* Binary search for the first entry with threshold >= r. The last threshold is
 * UINT32_MAX, so there always is one. */
static const struct start *pick_start(uint32_t r)
{
    uint32_t lo = 0, hi = N_STARTS - 1;
    while (lo < hi) {
        uint32_t mid = lo + (hi - lo) / 2;
        if (starts[mid].threshold < r)
            lo = mid + 1;
        else
            hi = mid;
    }
    return &starts[lo];
}

static const struct trans *pick_transition(const struct state *s, uint32_t r)
{
    const struct trans *t = &transitions[s->first];
    uint32_t lo = 0, hi = s->count - 1;
    while (lo < hi) {
        uint32_t mid = lo + (hi - lo) / 2;
        if (t[mid].threshold < r)
            lo = mid + 1;
        else
            hi = mid;
    }
    return &t[lo];
}

/* Appends a word to the output; returns nonzero if it ends a sentence. */
static uint32_t append(uint32_t id, int space)
{
    const struct word *w = &words[id];
    uint32_t n = w->len_flags & ~SENTENCE_END;
    if (space)
        out[len++] = ' ';
    memcpy(out + len, blob + w->offset, n);
    len += n;
    return w->len_flags & SENTENCE_END;
}

int main(void)
{
    const struct start *s;
    const char *p;
    uint32_t state, sentence_end;
    int i;

    seed();
    len = sizeof content_header - 1;
    memcpy(out, content_header, len);

    s = pick_start(random32());
    append(s->word_a, 0);
    sentence_end = append(s->word_b, 1);
    state = s->state;

    for (i = 0; i < MAX_WORDS && state != NONE; i++) {
        const struct trans *t;
        if (i >= MIN_WORDS && sentence_end)
            break;
        t = pick_transition(&states[state], random32());
        sentence_end = append(t->word, 1);
        state = t->next;
    }

    for (p = out; len > 0;) {
        ssize_t n = write(STDOUT_FILENO, p, len);
        if (n <= 0)
            return 1;
        p += n;
        len -= (size_t)n;
    }
    return 0;
}
